version: '2'

services:

    main:

        image: puffinrocks/wallabag:latest
        depends_on:
            - db
        ports:
            - 80
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST
            - LETSENCRYPT_EMAIL
            - LETSENCRYPT_TEST
            - MYSQL_ROOT_PASSWORD=wallaroot
            - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
            - SYMFONY__ENV__DATABASE_HOST=db
            - SYMFONY__ENV__DATABASE_PORT=3306
            - SYMFONY__ENV__DATABASE_NAME=wallabag
            - SYMFONY__ENV__DATABASE_USER=wallabag
            - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
        networks:
            - front
            - back
            - default
        volumes:
            - main_data:/var/www/wallabag
        tmpfs:
            - /run
            - /tmp

    db:
        image: puffinrocks/mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=wallaroot
        volumes:
            - db_data:/var/lib/mysql

volumes:
    main_data:
    db_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
